higakikeita/freemarket_sample_60ce

.gitignore
app/controllers/application_controller.rb
app/controllers/products_controller.rb
app/views/products/_header.html.haml
app/views/products/_products.html.haml
app/views/products/index.html.haml
config/routes.rb

サーバーと通信が可能なユーザーとパスワードをあらかじめ設定しておき、それを知っているユーザーのみがWebアプリーションを利用できるようにする
セキュリティ上の観点から必要な実装であるため

BASIC認証の設定

---

README.md

README内にDB設計を記述しました。
DB設計を記述する必要があるため。

readme.edit

---

README.md

README内、DBに関してのマークダウン記述修正
README内、DBに関してのマークダウン記述に不備があったため。

マークダウン記述の編集

---

app/assets/stylesheets/_registration.scss
app/assets/stylesheets/application.scss
app/controllers/registration_controller.rb
app/views/registration/index_step0.html.haml
app/views/registration/index_step1.html.haml
config/routes.rb

会員登録画面の step0 step1のビューファイル（haml,scss)
・サーバーサイドと連携しながら進めるためビュー画面単体で作成
・モデル等と連携していない状態で仮のビューを作成しているためform_forなどのメソッドは利用していません。
・上記に伴い、生年月日のプルダウンも仮の状態となっております。

[WIP]registration_view_step0,step1

---

Gemfile.lock
config/deploy.rb

capistranoの設定を変更した。deploy.rbでsecret.ymlを参照するように記述を変更した
secret.ymlの内容をgitで管理しないようにしていたため　自動デプロイを行っても本番環境に送られていなかったため

[WIP]自動デプロイ記述の追加

---

app/assets/stylesheets/products.index.scss
app/views/home/top.html.haml

出品ボタンにリンクを設定する
トップページから商品出品ページへ移動出来るようにするため。

出品ボタンにリンクを貼る

---

app/models/product.rb

本番環境でエラーの元となるモデルの記述を削除する
画像投稿テストを優先させるため　

[WIP]商品出品サーバサイド3

---

Gemfile
Gemfile.lock
app/controllers/products_controller.rb
app/models/category.rb
app/models/product.rb
app/views/products/new.html.haml
db/migrate/20200114134313_create_products.rb
db/migrate/20200120100937_create_categories.rb
db/schema.rb

商品出品に関する項目について　値が入力出来るようにモデル及びマイグレーションファイルを整えた。選択項目が決まっている箇所はenum及びactive_hashにて記載、自由入力の箇所はバリデーションを記載した。
商品出品の値を入力し、データを取得出来るようにするため。正しいデータだけをデータベースに保存するよう制約をかける必要があるため

[WIP]商品出品ページモデル修正

---

app/assets/stylesheets/_new.scss
app/views/products/new.html.haml

カテゴリー項目のボックスをcollection_selectにしたことによるビューの崩れの修正、ボックスの初期表示を　"---"に統一した
今後の実装をスムーズにするため。
https://gyazo.com/d4b27ce7bdb2e29226d3416072eb19d7

[WIP]商品出品ページビューの調整

---

config/initializers/carrierwave.rb

画像投稿における条件分岐の修正。本番環境でのみS3に画像が保存出来るように記述を変更した
デプロイ担当者以外の開発環境からも画像を投稿出来るようにするため。

Carrierwaveの設定の修正

---

app/assets/javascripts/application.js
app/assets/javascripts/previews.js
app/views/products/new.html.haml

出品ページの画像のプレビューを表示させる実装
選択した画像を投稿画面で確認するため
確認用→https://gyazo.com/a53e219fee432d6c1c6dc9c290d54ef0

[WIP]商品出品プレビューJS

---

app/views/products/new.html.haml
app/views/users/index.html.haml

マイページにヘッターとフッターをつけた
マイページからもヘッターなどのリンクに飛べるようにするため
確認用
https://gyazo.com/238db5be4c597dfac73017c5f8aed6a8
https://gyazo.com/acfe6f8fb1ad600b8515dc6ac0428e5d

[WIP]header footer to mypage

---

app/assets/stylesheets/_products-show.scss
app/controllers/comments_controller.rb
app/controllers/products_controller.rb
app/models/comment.rb
app/models/product.rb
app/views/products/show.html.haml
config/routes.rb
db/migrate/20200125120245_create_comments.rb
db/schema.rb

商品詳細に紐づくコメント機能の実装
ユーザーが商品についてコメント出来るようにするため

[WIP]商品詳細ページのコメント機能の実装

---

app/assets/stylesheets/_products.edit.scss
app/assets/stylesheets/application.scss
app/controllers/products_controller.rb
app/views/products/edit.html.haml
config/routes.rb

出品された商品を編集する機能の実装に関わるルーティングの設定及びコントローラの記述、仮置きビューファイルの作成
出品された商品を編集する機能を実装するための準備のため
仮置きビュー
https://gyazo.com/c709232b4475dbea3f770af3abd8fd3e

[WIP]商品編集ページサーバサイド#1

---

app/controllers/products_controller.rb
app/models/product.rb
app/views/products/edit.html.haml
config/routes.rb

出品済みの商品の削除機能の実装
削除できるようにするため
＊削除後に飛ぶページは今の所トップページになっております

[WIP]add-destroy

---

app/assets/stylesheets/_header.scss
app/views/home/top.html.haml
db/schema.rb

ログイン前後でヘッダーを切り替えるようにしました。
ログイン前後でヘッダーの内容が異なるため。

ログイン前後でのヘッダー切り替え実装

---

app/assets/stylesheets/_mixin.scss
app/assets/stylesheets/_products-show.scss
app/assets/stylesheets/_products.edit.scss
app/views/products/new.html.haml
app/views/products/show.html.haml
db/migrate/20200119080750_drop_table_credit_cards.rb
db/schema.rb

商品出品の流れに乗っ取り、ページ遷移上のビューの調整を行った。
ユーザー登録実施後の条件分岐の実装を迅速に行うため
ビューの確認
[![Image from Gyazo](https://i.gyazo.com/63a164ce44194dceeefd789bad5c95c2.gif)](https://gyazo.com/63a164ce44194dceeefd789bad5c95c2)

商品詳細ページビューの修正#3

---

app/models/product.rb
app/views/products/show.html.haml
db/migrate/20200111042708_devise_create_users.rb
db/schema.rb

マイグレーションファイルの修正、userとproductのアソシエーション設定
ビューファイル微調整
ユーザーログイン時とログインしていない時の条件分岐に備える実装をするための準備が必要であるため

ユーザーログイン条件分岐のための準備

---

app/views/home/_header_login.html.haml
app/views/products/edit.html.haml

編集ページのキャンセルボタンを押した時のリンク先を実装
前の商品ページに戻れるようにするため

[WIP]chancel_button

---

app/views/registration/index.html.haml

turbolinksを部分的にオフするための記述
turbolinksにより、JSが意図した動作をしなかったため

turbolinksを部分的にオフするための記述

---

app/controllers/products_controller.rb
app/views/products/edit.html.haml

画像データを商品情報ページで編集する機能の実装
商品情報の変更において画像情報の変更は必須であるため

商品情報の画像の編集の実装

---

config/secrets.yml

API導入に伴う環境変数の設定を行った
本番環境での動作確認を円滑に行うため

シークレットymlファイルの変更

---

app/controllers/users_controller.rb
config/routes.rb
db/schema.rb

マイページ（本人確認ページ）のビュー実装に関連してコントローラー、ルーティングの設定を行う。
ユーザー登録情報の編集が含まれるマイページ（本人確認ページ）のビュー実装の下準備のため。

マイページのビュー実装に伴うサーバーサイドの設定

---

db/schema.rb
spec/controllers/comments_controller_spec.rb
spec/controllers/products_controller_spec.rb

商品詳細ページサーバサイドコントローラの単体テストコードを記載
動作確認をするため、コードの記述をテストする必要があるため

商品詳細ページコントローラテスト

---

app/assets/stylesheets/_mypage-edit.scss
app/assets/stylesheets/application.scss
app/views/products/_bottom.html.haml
app/views/products/_sell-tab.html.haml
app/views/products/index.html.haml
app/views/users/edit.html.haml

ビューファイルの作成と、同じ記述がある箇所（bottom, sell-tab）は部分テンプレートで対応。
https://gyazo.com/5d01fb25b5927f2101a6ba08ba7b7084
マイページより本人情報の確認と変更を行えるようにする為。

マイページ（本人確認ページ）のビュー実装

---

app/assets/stylesheets/_registration.scss
app/controllers/users_controller.rb
app/views/devise/sessions/logout.html.haml
app/views/users/index.html.haml
config/routes.rb

ログアウト機能の実装

---

spec/controllers/products_controller_spec.rb

出品した商品を削除するコントローラのテスト
削除機能コントローラのコードが正常に動作するかテストする必要があるため

商品編集削除テストコード

---

app/controllers/users_controller.rb
app/views/home/_header_login.html.haml
app/views/users/show.html.haml
config/routes.rb

マイページのリンクを設定する。
※ [index.html.haml] → [show.html.haml] に変更しています
https://gyazo.com/fdee17f29c814ce13fcfc55539adafc5
マイページに関するリンク設定を行なっていなかった為。

マイページのリンク設定の修正

---

README.md
db/migrate/20200111042708_devise_create_users.rb
db/migrate/20200111055028_create_addresses.rb
db/migrate/20200114134313_create_products.rb
db/schema.rb

What
-Gem変更:なし
-DB変更：あり
　-migration file/README)の記述変更
*王子さん、こちらマージされ次第、ER図の変更をお願いします。
-機能変更：なし
-スクショ：なし
-その他：なし
Why
機能実装が進むにつれて、DBの編集が必要であったため

DB(migration file/README)変更

---

spec/controllers/products_controller_spec.rb
spec/factories/products.rb
spec/models/product_spec.rb

- Gem変更 : なし
- DB変更：なし
- 機能変更：productsコントローラー(indexアクション)の単体テストを行う。
- スクショ：https://gyazo.com/e54e724742754e8dc4eeac467fecbec8
- その他：上記スクショ ”GET #index”が該当箇所です
ビューの変遷とインスタンス変数について、期待する値になっているか確認をする為。

productsコントローラー(indexアクション)の単体テスト

---

app/models/creditcard.rb
db/migrate/20200111055028_create_addresses.rb
db/schema.rb
spec/factories/creditcard.rb
spec/models/creditcard_spec.rb
spec/rails_helper.rb
spec/support/controller_macros.rb

-Gem変更:なし
-DB変更：なし
-機能変更：
①テストコードの記入（クレジットカードのバリデーションテスト）
　spec/models/creditcard_spec.rb　に追加しています
②Creditcardモデル（app/models/creditcard.rb）にバリデーションを追加
　・カード番号やセキュリティコードはinteger
　・カード番号は16桁
　・セキュリティコードは3もしくは4桁）
③deviseをRSpecでも使えるようにするためにディレクトリ、ファイルを追加
　・ディレクトリ：spec/support
　・ファイル：spec/support/controller_macros.rb
-スクショ：
クレジットカードのバリデーションテストの結果
https://gyazo.com/9585b504c88b5807b2cc30ec83b6d1d3
アプリの完成精度を高めるためにはテストが必要であるため

[WIP]テスト_会員登録・クレジットカードのバリデーション

---

app/assets/stylesheets/_mixin.scss
app/assets/stylesheets/_new.scss

scssファイルにおいて重複する記述を修正した。
追加実装をしやすくするために記述の整理が必要であったため

商品出品ページビューの整備

---

app/models/user.rb
db/schema.rb
spec/factories/user.rb
spec/models/user_spec.rb

-Gem変更:なし
-DB変更：なし
-機能変更：
①テストコードの記入（会員登録のバリデーションテスト）
　spec/models/user_spec.rb　に追加しています
②userモデル（app/models/user.rb）にバリデーションを追加
　・空欄NG（presence: true）
　・email 空欄NG、重複NG、@を入れる形になっているか
　・password 空欄NG、最低7文字、英数字がどちらも入る形になっているか
-スクショ：
会員登録のバリデーションテストの結果
https://gyazo.com/03ba1aa54d6e991b71958174e15b5fbc
WHY
アプリの完成精度を高めるためにはテストが必要であるため

[WIP]テスト_会員登録のバリデーション

---

app/models/address.rb
config/application.rb
config/locales/devise.ja.yml
config/locales/ja.yml
spec/models/address_spec.rb
spec/models/creditcard_spec.rb
spec/models/product_spec.rb
spec/models/user_spec.rb

Gem変更:なし
DB変更：なし
機能変更：英文だったエラーを日本語表示に変更、それに伴いテストコードも修正
スクショ：https://gyazo.com/cc4eb5b3fd65b2d16d8ab44407aac4bb
その他：
「config/locales」ディレクトリに以下2つのファイルを新規作成し、日本語表示のためのエラーを追記
・devise.ja.yml
・ja.yml
アプリの完成度をあげるため

[WIP]エラーの日本語化

---

db/migrate/20200111055028_create_addresses.rb
db/schema.rb

DB変更:有り　
ユーザー登録バリデーション一部削除をした
動作確認をしてみたところエラーが発生するため

validationの削除

---

app/assets/javascripts/carousel.js
app/views/layouts/application.html.haml

turbolinksを読み込む設定のjsファイルを修正した。
turbolinksを削除した際に読み込みエラーが起きたため。

turbolinks削除に伴うjsファイルの修正

---

app/assets/stylesheets/_mypage-edit.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/mypag_side.scss
app/assets/stylesheets/mypage_main.scss
app/assets/stylesheets/mypage_side.scss
app/views/users/_mypage_side.html.haml
app/views/users/profile.html.haml

DB:変更無し
gem:無し
ユーザープロフィール編集ページのマークアップを行う
ユーザープロフィール編集機能実装のため、最低限のイメージ構築作業が必要であったため
ビュースクショ
https://gyazo.com/03280c0214cebbebe38bdfe1780798e9

[WIP]ユーザープロフィール編集ページマークアップ

---

app/assets/javascripts/nav-list.js
app/assets/stylesheets/_header.scss
app/assets/stylesheets/_mixin.scss
app/views/home/_header_login.html.haml
app/views/home/_header_unlogin.html.haml
app/views/home/_nav-brand.html.haml

- Gem変更: なし
- DB変更：なし
- 機能変更：TOPページの「ブランドから探す」の見た目の実装を行う。リンク先は未実装。
- スクショ：https://gyazo.com/ab991edc3995643b2541e8be2416f632
ユーザーがブランドから絞り込みができるようにする為。

TOPページ_商品ブランドの実装

---

app/controllers/application_controller.rb
app/controllers/products_controller.rb
app/controllers/users_controller.rb
app/views/home/_header_login.html.haml

- Gem変更: なし
- DB変更：なし
- 機能変更：なし
- スクショ：https://gyazo.com/b295efcd5829d656c691173916415c13
- その他： ログアウト後のno method errorの改修をする為、コントローラーの再設定を行う。
- 問題：ログアウト後のno method error
- 原因：コントローラーで変数の定義がされていなかった為。
- 解決方法：application_controller にて定義する。

ログアウト後のno method errorの改修

---

app/controllers/users_controller.rb
app/views/users/profile.html.haml
config/routes.rb

form_forのPATHの設定及びsubmitボタンの実装
PATCHメソッドの設定
ユーザプロフィールを編集する際に必要となる設定であるから。

ユーザプロフィール編集ページサーバサイド

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/category.scss
app/controllers/categories_controller.rb
app/views/categories/index.html.haml
app/views/home/_header_login.html.haml
app/views/home/_header_unlogin.html.haml
config/routes.rb

- Gem変更 : なし
- DB変更：なし
- 機能変更：categories_controller および 関連するビューファイルの作成
- スクショ①：https://gyazo.com/472acd660a28700612c92f478b64ce9c
- スクショ②：https://gyazo.com/89b3d814bec80e090937839bb85fb330
- その他：カテゴリー一覧表示ページを表示させるまでの最低限のサーバーサイドの設定を行う。
　　　　動作確認を行う為、ビューファイルに関しては最低限の実装を行った。
　　　　HTMLとSCSS、リンクの設定などは後の実装で行う。
カテゴリー一覧ページより商品を絞り込めるようにする為

カテゴリー一覧表示_サーバーサイド設定

---

app/views/categories/index.html.haml
app/views/users/profile.html.haml
config/breadcrumbs.rb

以下のページへのパンくず追加
・ユーザープロフィール編集画面（/profile）
・カテゴリ一覧（/categories）
Gem変更: なし
DB変更：なし
機能変更：パンくずリストの追加
スクショ：
https://gyazo.com/33826e420887d652a48995294ba65cd4
https://gyazo.com/c2a8fce68fa3a11a3ed6bb2b637d90fa
・必要機能のため
・明日のスプリントレビューに向けて

[WIP]パンくず追加

---

app/assets/stylesheets/_header.scss
app/views/home/_header_login.html.haml

商品検索機能実装に伴いヘッダーのビューが崩れていたので修正した
商品検索する際にユーザーの利便性を高めるため
スクショ
https://gyazo.com/071b03bc683f4dce9e586c88d8292121

商品検索機能実装に伴うログインヘッダービューファイルの調整

---

app/assets/javascripts/mypage_tubs.js
app/assets/stylesheets/user.scss
app/views/users/show.html.haml

マイページのタブの切り替え部分の実装です
Gem変更: なし  
DB変更：なし
マイページを作った時にその部分を後から実装するにしていたから
確認
https://gyazo.com/72ee89df66f48e9f1b23b648fcd21977

Mypageのタブのところのjs

---

app/assets/stylesheets/_header.scss
app/views/home/_header_unlogin.html.haml

非ログイン時のヘッダーにおいて商品検索機能の実装
非ログインユーザも商品検索は出来るようにするため
スクショ
https://gyazo.com/278eee4d0dc6dddbbc7f047de2599037

非ログイン時のヘッダーの修正

---

app/assets/javascripts/category.js
app/assets/stylesheets/category.scss
app/views/categories/index.html.haml

- Gem変更: なし
- DB変更：なし
- 機能変更：カテゴリー一覧表示のビューファイル追加
- スクショ：https://gyazo.com/a4729c990ead5418886bbef2497dca1c
- その他：各カテゴリごとの詳細ページへのリンクは余裕があれば別ブランチで実装する
カテゴリ一から商品の絞り込みをできるようにする為

カテゴリー一覧表示_ビューファイル作成

---

app/controllers/products_controller.rb
app/models/image.rb

商品出品時に画像が空では出品出来ないようにバリデーションを設定
商品出品機能に画像表示は必須であるため。

商品出品ページサーバサイド#4

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/search_view.scss
app/views/products/searches/index.html.haml

- Gem変更:なし
- DB変更：なし
- 機能変更：検索結果のビューの作成
- スクショ：https://gyazo.com/00c489921b41c615c5f697cfbe324838
- その他：なし
必要な機能であるため
**検索結果後の、サイドバーの検索欄は、別のブランチで実装します**

[WIP]検索結果ビュー

---

Gemfile
Gemfile.lock
app/assets/stylesheets/search_view.scss
app/controllers/products/searches_controller.rb
app/controllers/products_controller.rb
app/views/home/_header_login.html.haml
app/views/home/_header_unlogin.html.haml
app/views/products/searches/index.html.haml
config/routes.rb

gem: ransack使用
商品詳細検索機能の実装
ヘッダーの検索機能も変更
並び替え、キーワード、価格の範囲、クリアボタンまでの実装(条件は今後追加します）
商品を様々な条件で検索することによりユーザーの利便性が向上するため
スクショ
（価格の範囲検索)
https://gyazo.com/c64f4860913d2a655627e5439a2a88db
(価格安い順検索)
https://gyazo.com/d8d692480f847306d730336c659146cc
(キーワード検索)
https://gyazo.com/9fa6662146a36c41faceadb56c30835a

商品詳細検索機能サーバサイド#1

---

app/assets/stylesheets/search_view.scss
app/controllers/products/searches_controller.rb
app/views/products/searches/index.html.haml

商品詳細検索ページのビュー調整を実施
検索しやすい見た目はユーザーの利便性を高めるため
スクショ
https://gyazo.com/6bbdb99d63431f8306b99156a82225ce

商品詳細検索ビューの調整#1

---

app/controllers/application_controller.rb

gem ransack を導入した際にapplication_controllerにもransackの内容を反映させた
トップページにransackの内容を反映させるため

gem　ransack導入に関するエラーの解消

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_registration.scss
app/controllers/users/omniauth_callbacks_controller.rb
app/models/user.rb
app/views/devise/sessions/new.html.haml
app/views/registration/index.html.haml
config/initializers/devise.rb
config/secrets.yml

- Gem変更:gem 'omniauth-twitter'
- DB変更：なし
- 機能変更：twitterのAPIを利用した新規登録＋ログイン
- スクショ：
ログイン機能（新規登録後）
https://gyazo.com/e7c7bdd50d090e2d98b747119c855cb3
*新規登録は自分のtwitterアカウントとアドレスが入ってきているので、割愛します。
- その他：こちらをマージ次第、投稿機能を追加します。
Twitter投稿機能との連携を目指すため。

Twitter認証機能追加

---

app/controllers/likes_controller.rb
app/controllers/products_controller.rb
app/models/like.rb
app/models/product.rb
app/models/user.rb
app/views/products/show.html.haml
config/routes.rb
db/migrate/20200229102542_create_likes.rb
db/schema.rb

商品へのいいね昨日の追加
いいね機能があったほうがいいね
確認
→https://gyazo.com/fc79b77060ff8d17d05f61360233a363

Likes いいねのサーバーサイド

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/ready.scss
app/controllers/users_controller.rb
app/views/home/_header_login.html.haml
app/views/users/_mypage_side.html.haml
app/views/users/ready.html.haml
config/routes.rb

実装していないページは「工事中」のビューが表示されるようにサーバサイド設定をした
実装していないページのリンクがエラー表示となるため。
仮置きビュースクショ
[![Image from Gyazo](https://i.gyazo.com/50cc54ad9227c1f6fffb5d892ea39ca4.png)](https://gyazo.com/50cc54ad9227c1f6fffb5d892ea39ca4)

[WIP]リンク未設定画面の作成サーバサイド

---

README.md
app/assets/stylesheets/ready.scss
app/views/users/ready.html.haml

実装していないページのリンクに「工事中」のページを作成。
CSSでアニメーションコーディングを実施
リンク先のページが無い場合エラー表示となり、見た目がよろしくないため
スクショ
[![Image from Gyazo](https://i.gyazo.com/7f4f373e2a804adec3558f31713c0133.gif)](https://gyazo.com/7f4f373e2a804adec3558f31713c0133)
[![Image from Gyazo](https://i.gyazo.com/51543bf243cea184b5abb171dde816cd.gif)](https://gyazo.com/51543bf243cea184b5abb171dde816cd)

工事中アニメーションページの作成

---

app/assets/stylesheets/search_view.scss

商品検索表示ページのビュー表示を修正した
サムネイルとサムネイルの間隔が狭いと見辛いため
スクショ
[![Image from Gyazo](https://i.gyazo.com/56f78e69d2b747efeeb30fcb54a910e9.png)](https://gyazo.com/56f78e69d2b747efeeb30fcb54a910e9)

商品検索表示ビュー修正

---

app/assets/stylesheets/_products-show.scss
app/views/likes/_like.html.haml
app/views/products/show.html.haml

いいね機能のviewの変更
非同期などは未実装なのでリロードするといいね押せてます
viewが変だったから
https://gyazo.com/a0e589af3d142f74ae007d6cb5b5c0ec

viewをpartialにした

---

Gemfile
Gemfile.lock
config/application.rb
config/schedule.rb
lib/tasks/product_task.rb

- Gem変更 : 'whenever'
- DB変更：なし
- 機能変更：下記内容を自動で繰り返す、タイムセール機能を実装した。
　　　　　　①毎週末（土日）に全商品が10％オフになる
　　　　　　②毎月曜日に元値に戻す
- スクショ：https://gyazo.com/dff1137fc7ebed411390f11e4ed28155
- その他：本番環境での実装（capistranoとの連携）は別途作業が必要になる為、
　　　　   ひとまず開発環境でのみ機能する仕様にしている。
購買意欲をあげる工夫の一環として追加実装している。

タイムセール機能の実装（＊開発環境のみ）

---

app/assets/stylesheets/_products.edit.scss
app/views/products/show.html.haml

- Gem変更:なし
- DB変更：なし
- 機能変更：Twitterにリンクシェア機能追加（出品者のみ）
- スクショ：
投稿アクション
https://gyazo.com/4120b2b68c57244140a8f9499563ab54
投稿後（Twitter)
https://gyazo.com/c8145fb1f786ac8b8ac52388218a3abc
- その他：
ユーザーの満足度向上のため

Twitter(投稿機能）

---

app/assets/stylesheets/_products-show.scss
app/views/likes/_like.html.haml
app/views/products/show.html.haml

いいね機能といいねボタンをリンクさせた
いいねボタンのところをpartialにした
Userの使用感を向上させる為
https://gyazo.com/08a6b8ef7151165d56007f60304d9a16
＊非同期は未実装なのでリロードするといいねされます

Add likes#2

---

README.md
app/assets/stylesheets/slick.scss
app/views/products/index.html.haml

- Gem変更: なし
- DB変更：なし
- 機能変更：REAMDEの編集とTOPページ画像の文字サイズや幅の微調整
- スクショ：https://gyazo.com/6a8ea91986422ee494d2b0153749c315
アプリの説明文として必要な為

README編集&TOP画像微調整
